### ISSUE TITLE
Is it still maintained!!

### ISSUE THREAD

**Issue by debojitkakoti** [erichmond/ruby-agi#1]
Hi I just come across to this repository, want to know is it still maintained? I need agi library in ruby to use in our application! Thanks in advance.

**Comment by erichmond** [comment]
Hello,

Sorry, it is not maintained and I have since moved on from the project that this was used in, so there will probably be no more support going forward.

Sorry about that.

**Comment by debojitkakoti** [comment]
Ok thanks for your reply. I ll fork it and see if I can contribute something.
